pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/

  integration-test:
    image: jnummelin/build-tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose up -d --build
      - bats tests/
      - docker-compose stop
      - docker-compose rm -f -v

  docker:
    image: plugins/docker:latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jnummelin/todo-example
    tag: ${DRONE_TAG}
    file: Dockerfile
    when:
      event: tag

  kontena:
    image: kontena/cli
    commands:
      - SSL_IGNORE_ERRORS=true kontena stack upgrade todo
    when:
      event: tag

services:
  database:
    image: mongo:3.2
